import Foundation
import GRDB

/// A meeting summary generated by the Anthropic API.
struct Summary: Codable, Identifiable {
    var id: String { meetingId }
    var meetingId: String
    var rawJson: String
    var executiveSummary: String?
    var title: String?
    var createdAt: Int64
}

// MARK: - GRDB Record Conformance

extension Summary: FetchableRecord, PersistableRecord {
    static let databaseTableName = "summary"

    enum Columns: String, ColumnExpression {
        case meetingId, rawJson, executiveSummary, title, createdAt
    }
}
